---
title: "Oysters Lit Review - Miller, K"
author: "Kelly Miller"
date: "2024-12-19"
output: pdf_document
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction to the microbial world

In a narrative that usually centers around plants, microorganisms are the unsung heroes of primary production. They work on a scale we cannot see, but the effects of their cumulative efforts are impossible to miss. Half of the oxygen in each breath we take has been produced by oceanic microbes [@pomeroy]. When we talk about the factors at play regulating ecological systems, when we talk about the cycling of nutrients between earth, water, sky, and us, it does us well to acknowledge that the drivers of biological processes are microorganisms. It's a microbial world; we're just living in it.

So let's zoom out from the macroscopic world for a moment to meet the three domains of life: Bacteria, Archaea, and Eukarya. As humans, we belong to the domain Eukarya, along with all other organisms whose cell(s) have genetic material enclosed in membrane-bound nuclei. In other words, in the most basic deliniation between all life forms present on Earth, we, in all of our complexity, are grouped with plants, fungi, and many microbial species (including some single-celled microbes), while the two remaining categories are exclusively microbes–prokaryotic[^1] microbes, to be specific.

[^1]: Prokaryotes: Unicellular microbes with free-floating genetic material in their cytoplasm. They can have organelles, like ribosomes (which all organisms have) or flagella (little extracellular hairlike-structures that enable movement for cells floating through the big void of the ocean or my stomach, for example), but they do not have membrane-bound organelles. A prokaryotic cell is like DNA/RNA-cytoplasm soup.

organisms, but prokaryotes as well–meaning they do not have organelles enclosed by membranes. Instead of performing metabolic pathways from start to finish, like how food is passed from mouth to esophagus to stomach to small intestine, etc., in our digestive systems, microorganisms are reliant on each other to achieve comparable biological processes.

This behavior led Dr. Farooq Azam from the University of California - San Diego to describe bacteria as the "ultimate swimming stomachs" [@pomeroy]. tried to articulate this phenomenon of However, let their simplicity not be misconstrued for irrelevance to our lives; microbes facilitate biological processes that we could not survive without. As for the communal aspect

Microbial species like \_\_\_\_\_\_\_ and \_\_\_\_\_\_\_ can break down metals that our systems could never dream of handling (cite cool example?). I share these two examples to highlight the diversity of the wonderful world of wee organisms.

like how our Bacterial and archaeal organisms often have

In each breath we breathe, about one half of the oxygen has been produced by oceanic microbes[@pomeroy]. It proves challenging to comprehend the sheer abundance of microorganisms that must be . For perspective, the number of stars in the universe is estimated to be 10\^21, while the number of bacteria in the ocean is

In other words, not only do all of the life forms recognizable to our eyes make up only a humble fraction of the living community on Earth; most of life exists as single cells that each perform In each breath we breathe, about one half of the oxygen has been produced by oceanic bacteria [@pomeroy]. (Thanks bacteria!) [The human hand and chemical fertilizers are not growing our food; microbes are, albeit with the optimization of good land husbandry practices.]

# Introduction to oyster farming

Oyster aquaculture on the eastern seaboard has risen (?) in the last several decades, after centuries of declining natural populations from over-harvesting (fact check?). While we face the deleterious ecological impacts of current industrial and agricultural production methods, oyster farming has been proposed as part of a re-imagined, more sustainable food system. Not only does oyster cultivation bypass certain agricultural issues like land scarcity; common scientific thought has it that farming oysters can provide benefits to the health of the ecosystem. These potential benefits include enhanced water quality, habitat provision to other marine species, and storm surge protection [@stevens2024].

While oysters do pull algae and larger plankton[^2] (macroplankton) from the water column, this is not the extent of their ability to improve water quality. The real magic makers live in oyster poop.

[^2]: microorganisms that are not motile; they move with the currents

are filter-feeders. They suck water through their gills, filtering out larger (?) plankton and algae while seawater passes through.

Oyster aquaculture has been practiced globally since ancient civilizations–the likes of Greece, Rome, and the Han Dynasty [@botta2020]. [quote about oyster abundance in the Hudson Bay in the 1800s?] While we face the deleterious ecological impacts of current industrial and agricultural production methods, oyster farming has been proposed as part of a re-imagined, more sustainable food system. Not only does oyster cultivation bypass certain agricultural issues like land scarcity; common scientific thought has it that farming oysters can provide benefits to the health of the ecosystem. These potential benefits include enhanced water quality, habitat provision to other marine species, and storm surge protection [@stevens2024].

benefits: promote biogeochemical cycling, storm surge protection

# Theory #1: Oysters enhance the biodiversity and composition of microbial communities in the seafloor.

# Theory #2: Oysters stimulate increased denitrification by sediment microbiota.

## Summary of Ray & Fulweiler paper, "Meta-analysis of oyster impacts on coastal biogeochemistry"

Oyster aquaculture increases the cycling of nitrogen in marine systems by stimulating denitrifying bacteria and archaea.This improves water quality, with the trade-off of releasing a small amount of nitrous oxide (N~2~o) into the atmosphere [@ray2021].

Testing another citation [@feinman2018].

## Citations
